server:
    port: 8080

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
    application:
        name: gateway-service
    cloud:
        discovery:
            enabled: true
        gateway:
            routes: 
            - id: auth-service-id
              uri: lb://auth-service
              predicates:
                - Path=/student/**
            discovery:
              locator:
                lower-case-service-id: true
                enabled: true