server:
    port: 8080

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
    application:
        name: gateway-service
    cloud:
        discovery:
            enabled: true
        gateway:
            globalcors:
              add-to-simple-url-handler-mapping: true
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "http://localhost:4200/"
                  allowedHeaders: "*"
                  allowedMethods:
                  - GET
                  - POST
            routes: 
            - id: student-service-id
              uri: lb://student-service/
              predicates:
                - Path=/student/**
            - id: teacher-service-id
              uri: lb://teacher-service/
              predicates:
                - Path=/teacher/**
            - id: course-service-id
              uri: lb://course-service/
              predicates:
                - Path=/course/**
            discovery:
              locator:
                lower-case-service-id: true
                enabled: true